name: MLtotenv
dependencies:
- python==3.7.10
- pip
- matplotlib
- "ipython<6"
- notebook
- ipywidgets
- pip:
  - keras
  - h5py
  - tensorflow
  - scipy
  - uproot3
  - tqdm
  - deepdish
  - sklearn
  - pandas
  - uproot_methods
  - uproot3

